fixes #27
jawordpressorg/plugin-handbook pull request #28
Opened 2024-05-28 07:37 UTC by stein2nd

2024-05-31 12:37 UTC, t-hamano requested changes

2024-05-31 12:37 UTC, t-hamano commented on plugins/settings.md
> +WordPress は、管理インターフェイスを簡単に構築でき、安全で、WordPress の管理設計と一貫したものにするために、2つのコア API を提供しています。
```suggestion
WordPress は、管理インターフェースを簡単に構築でき、安全で、WordPress の管理設計と一貫したものにするために、2つのコア API を提供しています。
```

[用語集](https://translate.wordpress.org/locale/ja/default/glossary/)に基づいた修正

2024-05-31 12:37 UTC, t-hamano commented on plugins/settings.md
> +[オプションAPI](https://developer.wordpress.org/plugins/settings/options-api/) は、シンプルなキー/バリュー・システムを使ったデータ管理に重点を置いています。
```suggestion
[オプション API](https://developer.wordpress.org/plugins/settings/options-api/) は、シンプルなキー/バリュー・システムを使ったデータ管理に重点を置いています。
```

2024-05-31 12:37 UTC, t-hamano commented on plugins/settings.md
> +設定APIとオプションAPIを使用した[カスタム設定ページの構築](https://developer.wordpress.org/plugins/settings/custom-settings-page/)の完全な例を参照してください。
```suggestion
設定 API とオプション API を使用した[カスタム設定ページの構築](https://developer.wordpress.org/plugins/settings/custom-settings-page/)の完全な例を参照してください。
```

2024-06-02 02:48 UTC, stein2nd commented on plugins/settings.md
> +設定APIとオプションAPIを使用した[カスタム設定ページの構築](https://developer.wordpress.org/plugins/settings/custom-settings-page/)の完全な例を参照してください。
先程、「Suggested change」を反映したものをcommitしました。

2024-06-03 14:43 UTC, t-hamano approved these changes
LGTM!

2024-06-03 14:43 UTC, merged