fixes #29
jawordpressorg/plugin-handbook pull request #30
Opened 2024-05-28 08:10 UTC by stein2nd

2024-05-31 12:34 UTC, t-hamano requested changes

2024-05-31 12:34 UTC, t-hamano commented on plugins/security.md
> +このコンテンツは、共通APIハンドブックの[セキュリティページ](https://developer.wordpress.org/apis/security/)に移動しました。
```suggestion
このコンテンツは、共通 API ハンドブックの[セキュリティページ](https://developer.wordpress.org/apis/security/)に移動しました。
```

2024-06-02 02:49 UTC, stein2nd commented on plugins/security.md
> +このコンテンツは、共通APIハンドブックの[セキュリティページ](https://developer.wordpress.org/apis/security/)に移動しました。
先程、「Suggested change」を反映したものをcommitしました。

2024-06-03 14:44 UTC, t-hamano approved these changes
LGTM!

2024-06-03 14:44 UTC, merged