fixes #33 Translated metadata.md
jawordpressorg/plugin-handbook pull request #34
Opened 2024-05-28 12:36 UTC by stein2nd

2024-05-31 12:31 UTC, t-hamano requested changes

2024-05-31 12:31 UTC, t-hamano commented on plugins/metadata.md
> +WordPress に於けるメタデータの多対一の関係を考えると、オプションはかなり無限大です。望むだけ多くのメタオプションを持つことができ、そこにあらゆるものを保存することができます。
```suggestion
WordPress におけるメタデータの多対一の関係を考えると、オプションはかなり無限大です。望むだけ多くのメタオプションを持つことができ、そこにあらゆるものを保存することができます。
```

「於ける」は日本語訳であまりみかけないので、ひらがなで良いと思います。

2024-06-02 02:50 UTC, stein2nd commented on plugins/metadata.md
> +WordPress に於けるメタデータの多対一の関係を考えると、オプションはかなり無限大です。望むだけ多くのメタオプションを持つことができ、そこにあらゆるものを保存することができます。
先程、「Suggested change」を反映したものをcommitしました。

2024-06-03 14:42 UTC, t-hamano approved these changes
LGTM!

2024-06-03 14:42 UTC, merged