fixes #35 Translated taxonomies.md
jawordpressorg/plugin-handbook pull request #36
Opened 2024-05-28 13:01 UTC by stein2nd

2024-05-31 12:28 UTC, t-hamano requested changes

2024-05-31 12:28 UTC, t-hamano commented on plugins/taxonomies.md
> +**タクソノミー**とは、物事を分類/グループ化するための造語です。タクソノミーは、階層的（親/子）にもフラットにもなります。
```suggestion
**タクソノミー**とは、物事を分類/グループ化するための専門用語です。タクソノミーは、階層的（親/子）にもフラットにもなります。
```

「造語」は少し堅苦しいかなと思いました。

2024-06-02 02:50 UTC, stein2nd commented on plugins/taxonomies.md
> +**タクソノミー**とは、物事を分類/グループ化するための造語です。タクソノミーは、階層的（親/子）にもフラットにもなります。
先程、「Suggested change」を反映したものをcommitしました。

2024-06-03 14:41 UTC, t-hamano approved these changes
LGTM!

2024-06-03 14:41 UTC, merged